#!/bin/bash
set -e

# Check if the user is root.
if [ $USER != "root" ]; then
	echo "Please run the script by root user."
	exit
fi

# Update and Upgrade the system system first
dpkg --add-architecture i386 # for running steam
apt update
apt upgrade -yyq

# Check if gdebi and xargs is pre-installed. If not, go ahead and install!
dpkg -l | grep -qw gdebi || apt install -yyq gdebi
dpkg -l | grep -qw xargs || apt install -yyq xargs

# Install Chrome.
if [ -f ./chrome.sh ]
then
/bin/bash ./chrome.sh
else
echo -e "\nchrome.sh not found!"
fi

# Install Discord.
if [ -f ./discord.sh ]
then
/bin/bash ./discord.sh
else
echo -e "\ndiscord.sh not found!"
fi

# Install Spotify.
if [ -f ./spotify.sh ]
then
/bin/bash ./spotify.sh
else
echo -e "\nspotify.sh not found!"
fi

# Get Hostname Information.
OS=$(hostnamectl | grep Operating | awk -F ": " '{print $2}')

# If the OS is Debian, run the scripts.
if [[ "$OS" == *"Debian"* ]]; then

	# Install the packages.
	if [ -f ./pkglist.txt ]
	then
		xargs apt install -yqq < pkglist.txt
	else
		echo -e "\npkglist.txt not found!"
		sleep 1
	fi

	# Install NVIDIA Drivers
	if [ -f ./nvidia.sh ]
	then
		/bin/bash ./nvidia.sh
	else
		echo -e "\nnvidia.sh not found!"
		sleep 1
	fi

fi

echo -e "Please do not forget to reboot now!"
echo -e "Also, execute localdebs and authenticator when in need"
#EOF