#!/bin/bash
set -e

# Set local user to uid 1000
LOCALUSER=$(id -un 1000)
TEMPD=$(mktemp -d)

# Check if the user is root.
if [ $USER != "root" ]; then
	echo "Please run the script by root user."
	exit
fi

echo "Applying sources.list patch."
cp /etc/apt/sources.list /etc/apt/sources.list.save
cp ./sources.list /etc/apt/sources.list

echo "Update and Upgrade the system system first."
sleep 1
dpkg --add-architecture i386 > /dev/null # for running steam
apt update > /dev/null
apt upgrade -yqq
sleep 1

echo "Check if gdebi and xargs is pre-installed. If not, go ahead and install!"
sleep 1
dpkg -l | grep -qw gdebi || apt install -yqq gdebi
dpkg -l | grep -qw xargs || apt install -yqq xargs
sleep 1

echo "Installing packages."
sleep 1
apt install -yqq simplescreenrecorder vlc gimp synaptic timeshift htop \
curl wget mtr resolvconf openvpn grsync gparted handbrake audacity vim \
vim-gtk python3-setuptools python3-pip python3-scapy aircrack-ng nmap gufw \
qbittorrent intel-microcode broadcom-sta-dkms network-manager-openvpn
#steam wireshark
sleep 1

echo "Installing NVIDIA drivers."
sleep 1
apt update > /dev/null
apt install nvidia-legacy-390xx-driver firmware-misc-nonfree -yqq
cp ./xorg.conf /etc/X11/xorg.conf
chmod 0644 /etc/X11/xorg.conf
echo "Applying patch to xsessionrc"
cat << EOF >> /home/$LOCALUSER/.xsessionrc
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96
EOF
cp /home/$LOCALUSER/.xsessionrc /etc/lightdm/nvidia.sh
chmod +x /etc/lightdm/nvidia.sh
cat << EOF >> /etc/lightdm/lightdm.conf

# Added for NVIDIA
[SeatDefaults]
display-setup-script=/etc/lightdm/nvidia.sh
EOF

chown $LOCALUSER:$LOCALUSER /home/$LOCALUSER/.xsessionrc
chmod +x /home/$LOCALUSER/.xsessionrc

echo "Applying patch for Touchpad as well."
sleep 1
mkdir /etc/X11/xorg.conf.d
cat << EOF > /etc/X11/xorg.conf.d/40-libinput.conf
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
EndSection
EOF
sleep 1

echo "Installing Google Chrome."
sleep 1
pushd $TEMPD
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /dev/null
gdebi -n google-chrome-stable_current_amd64.deb
sleep 1
echo "Installing Discord."
sleep 1
GETLINK=$(curl -sS "https://discord.com/api/download?platform=linux&format=deb"| awk '/https/,/deb/' | awk -F '\"' '{print $2}')
curl --progress-bar -sLo discord.deb $GETLINK
gdebi -n discord.deb
popd
rm -r $TEMPD
sleep 1

echo "Installing Spotify."
sleep 1
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
apt update && apt install spotify-client -yqq
sleep 1

echo "Script completed at $(date)"
echo "Do not forget to restart your computer!"
#EOF
