#!/bin/bash

read -p "Your main user account name please? " LOCALUSER

if [ $USER != "root" ]; then
	echo "Please run the script by root user."
	echo "Either su - root or sudo su"
	exit
fi
apt update
dpkg -l | grep -qw gdebi || apt install -yyq gdebi

# First, let's install a bunch of software:
apt install -yqq simplescreenrecorder vlc gthumb gimp \
synaptic git timeshift htop curl wget mtr resolvconf openvpn \
grsync gparted handbrake audacity vim vim-gtk \
python3-setuptools python3-pip python3-scapy aircrack-ng nmap \
gufw default-jdk default-jre

# Install all local .deb packages, if available:
if [ -d "/home/$LOCALUSER/Downloads" ]; then
	echo "Installing local .deb packages..."
	pushd /home/$LOCALUSER/Downloads
	#Download Tunnelbear OpenVPN configs
	wget https://s3.amazonaws.com/tunnelbear/linux/openvpn.zip && chown $LOCALUSER. openvpn.zip
	for FILE in ./*.deb
    do
        gdebi -n "$FILE"
    done
	popd
else
	echo $'\n'$"WARNING! There's no ~/Downloads directory."
	echo "Local .deb packages can't be automatically installed."
	sleep 3
fi

# Install Google Chrome:
mkdir /tmp/chrome
pushd /tmp/chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
gdebi -n google-chrome-stable_current_amd64.deb
popd
rm -rf /tmp/chrome

OS=$(hostnamectl | grep Operating | awk -F ": " '{print $2}')

if [[ "$OS" == *"MINT"* ]];
then
	echo "Flatpak comes pre-build with Linux Mint 18.3 and above!"
	echo "Adding Flatpak repo for GNOME Authenticator"
	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	echo "Installing GNOME Authenticator..."
	flatpak install -y flathub com.github.bilelmoussaoui.Authenticator
	echo "Done!"
else
	apt update
	apt install flatpak -yqq
	echo "Adding Flatpak repo for GNOME Authenticator"
	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	echo "Installing GNOME Authenticator..."
	flatpak install -y flathub com.github.bilelmoussaoui.Authenticator
	echo "Done!"
fi

if [[ "$OS" == *"Debian"* ]]; then
echo "Installing Wi-Fi and GPU Drivers"
cp /etc/apt/sources.list /etc/apt/sources.list.save
echo "" > /etc/apt/sources.list
echo "
#

deb http://deb.debian.org/debian/ buster main contrib non-free
deb-src http://deb.debian.org/debian/ buster main contrib non-free

deb http://security.debian.org/debian-security buster/updates main contrib non-free
deb-src http://security.debian.org/debian-security buster/updates main contrib non-free

# buster-updates, previously known as 'volatile'
deb http://deb.debian.org/debian/ buster-updates main contrib non-free
deb-src http://deb.debian.org/debian/ buster-updates main contrib non-free

" >> /etc/apt/sources.list
apt update
apt install broadcom-sta-dkms bumblebee-nvidia primus libgl1-nvidia-glx -yyq
usermod -aG bumblebee $LOCALUSER
fi

# Clean and reboot now:
apt clean && apt autoclean && apt autoremove -y
echo $'\n'$"*** All done! Please reboot now. ***"
exit
